name: Build and Deploy to GHCR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the Docker image to GHCR
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/grafana-image-renderer:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Optional: Set the "latest" tag for the image
      - name: Tag and Push Latest
        run: |
          docker tag ghcr.io/${{ github.repository }}/grafana-image-renderer:latest ghcr.io/${{ github.repository }}/grafana-image-renderer:latest
          docker push ghcr.io/${{ github.repository }}/my-app:latest
